# Copy this file into one without .sample part and then populate it with actual values.
# Then you can create secret, by using command
# `sem create -f path/to/this/file`
# More info https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
apiVersion: v1alpha
kind: Secret
metadata:
  # Use this name to create this secret manually
  name: gcr-secret
data:
  # If you haven't set up k8s on google you need to do it first
  # Start with https://cloud.google.com/kubernetes-engine/docs/quickstart
  # Play with it and then you can use it with this project.
  # Check out https://docs.semaphoreci.com/article/72-google-container-registry-gcr as an example.
  # Also check out https://docs.semaphoreci.com/article/119-ci-cd-for-microservices-on-kubernetes
  # as example of k8s deploy.
  env_vars:
    # Id of your project
    # More info here https://cloud.google.com/resource-manager/docs/creating-managing-projects?visit_id=636878590586351739-3388570778&rd=1#identifying_projects
    - name: GCP_PROJECT_ID
      value: "your-gcp-project-id"
    # Default compute zone you've selected
    # https://cloud.google.com/compute/docs/regions-zones/#available
    - name: GCP_PROJECT_DEFAULT_ZONE
      value: "europe-west1-b"
  files:
    # You need to create service account and export json key file for it here https://console.cloud.google.com/iam-admin/serviceaccounts
    # to use in this file.
    - path: .secrets.gcp.json
      # Could be created by
      # - `base64 -w 0 /path/to/file` and put in
      # - upload in https://<your-namesace>.semaphoreci.com/secrets
      content: PASTE_BASE64_ENCODED_CONTENT_HERE
