# Copy this file into one without .sample part and then populate it with actual values.
# Then you can create secret, by using command
# `sem create -f path/to/this/file`
# More info https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
apiVersion: v1beta
kind: Secret
metadata:
  # Use this name to create this secret manually
  name: server-ormconfig-production
data:
  files:
  # Copy src/server/ormconfig.sample.json into ormconfig.production.json and populate with production values
  # You will need production connection settings in this config file.
  # In this eample heroku postgres database addon is used.
  # You will need to create heroku app and then add addon https://elements.heroku.com/addons/heroku-postgresql
  # Then you will be able to view database connection settings like described here https://devcenter.heroku.com/articles/heroku-postgresql#external-connections-ingress
  - path: ormconfig.production.json
    # Could be created by
    # - `base64 -w 0 /path/to/file` and put in
    # - upload in https://<your-namesace>.semaphoreci.com/secrets
    content: PASTE_BASE64_ENCODED_CONTENT_HERE
